import matplotlib.pyplot as plt
import pandas as pd
import numpy as np

class Monopoly:
    def __init__(self, year, total_population):
        self.year = year
        self.total_population = total_population
        
    def set_var(self):
        while True:
            try:
                if 2014<=self.year<=2024:
                        break
                else:
                    print("Invalid Year")
            except ValueError:
                print("Not a valid number")
        #Monopoly of for people above 8 Years of age i.e 85.5% of total population
        self.population_above_8 = self.total_population * (85.5/100)

        #Calculate the percent of areas where board game is available for sale
        self.available_population = self.population_above_8 * (60/100)

        self.player_population = self.available_population * (20/100)
        
        #MARKET SHARE
        if 2014<=self.year<=2017:
            self.market_share = (25/100)
            self.avg_price = 600             #Average price of Monopoly® board game (INR)
            self.bg_per_year = 0.012         #Number of board games purchased per individual per year
            self.exchange_rate = 60
            
        elif 2018<=self.year<=2020:
            self.market_share = (18/100)
            self.avg_price = 800
            self.bg_per_year = 0.009
            self.exchange_rate = 70
            
        elif 2021<=self.year<=2024:
            self.market_share = (10/100)
            self.avg_price = 1000
            self.bg_per_year = 0.007
            self.exchange_rate = 80
    
    def calculate(self):
        
        annual_sale_inr = self.player_population * self.bg_per_year * self.market_share * self.avg_price
        annual_sale_usd = (annual_sale_inr/self.exchange_rate)*1000
        return annual_sale_usd
    
if __name__=="__main__":
    year = int(input("Year (2014-2024): "))
    total_population = float(input("Enter population in millions:" ))
    monopoly = Monopoly(year, total_population)
    monopoly.set_var()
    print(f"Annual Revenue generated by Monopoly in India in {year} was {monopoly.calculate():.2f} millions")
    
    